### ISSUE TITLE
Feedback JWT isAdmin

### ISSUE THREAD

**Issue by ghispell** [WildCodeSchool/workshop-js-auth#2]
Bonjour, 

Il y a une erreur d'orthographe dans le fichier authController à la ligne 27 : 
{ sub: user.id, isAdmin: user.isAdmin } doit être écrit { sub: user.id, isAdmin: user.is_admin } pour que l'ajout d'item fonctionne avec la ligne 44 de l'itemController :   if (!req.auth.isAdmin) 

Merci !

**Comment by rocambille** [comment]
Merci @ghispell :)
